# Generated by Django 4.2.23 on 2025-09-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('usn', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('collegename', models.CharField(max_length=150)),
                ('offer_status', models.CharField(max_length=60)),
                ('started_date', models.CharField(max_length=60)),
                ('end_date', models.CharField(max_length=60)),
                ('project_report', models.CharField(max_length=60)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
