# Generated by Django 4.2.23 on 2025-09-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_internship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='collegename',
            new_name='college_name',
        ),
    ]
