# Generated by Django 4.2.23 on 2025-10-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
